var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                                                ",
   "                                                                 xx xxm         ",
   "                                                                x!!x!!x         ",
   "                                                               xx!!!!!xx        ",
   "                                    o o                o o      xx!!!xx         ",
   "                                                       xxx       xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                            o     xxx                       xx  ",
   "  xx                                                                         x  ",
   "  x                                       xxxxx                              x  ",
   "  x                           xxxxx                                        o x  ",
   "  x                                                                          x  ",
   "  x  @    xxxx        xxxxx                                                  x  ",
   "  xxxx                                                     xxxxxxx   xxxxxxxxx  ",
   "     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      !!!           ",
   "     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      !!!           ",
   "     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      !!!           ",
   "     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                               x!!!!!!!!!x                   xx    xxxxx    xx                                    ",
   "                               x!!!!!!!!!x                 xx       xxx       xx                                  ",
   "                               x!!!!!!!!!xxxxxxxxxx!!!!!!!!!!                 xx                                  ",
   "                               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                 xx                                  ",
   "                               xvxxxvxxxvxxxvxxvx!!!!!!!!!!!!                                                     ",
   "                                                xx!!!!!!!!!!!      o   o                                          ",
   "                                                 x!!     v !!                                                     ",
   "                                                 xvx       xx      x   x                                          ",
   "                                                            xxx  |   |   |  xx                                    ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxx!!!!!!xxxx                                      ",
   "                                                                  vxxxxxx            o       xxx                  ",
   "                                                                                   xxxxx     x x                  ",
   "                                                     x                                      ox                    ",
   "                                                     x                                      xx                    ",
   "                                                    xx                m                      x                    ",
   "                                                     x      o  o                             x                    ",
   "          x     xxxx                                 x                                      ox                    ",
   "                                                    ox     xxxxxx                           xx                    ",
   "                              oo                    xx                                       x                    ",
   "     @       x         x                             x                                       x                    ",
   "    xxx      x         x     xxxx                    x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x                             x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x                            x                x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x                            x                xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x                           x                               xx     xx                     ",
   "!!!!x x!!!!!!x         x                           x                                 xxxxxxx                      ",
   "!!!!x x!!!!!!x         x              xxxxxxxxxxxxxx                                                              ",
   "!!!!x x!!!!!!x         xxxxxxxxxxxxxxxx                                                                           ",
   "!!!!x x!!!!!!x         x                                                                                          "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  @                                                                                                           ",
   " xx                                                                                                           ",
   "                                                                                                              ",
   "                                                                                                              ",
   "      xx                                                                                                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "            xx                                                                                                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "        xx                                                                                                    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "    xx                                  xx xx                                                                 ",
   "                                       x!!x!!x                                                                ",
   "                                      xx!!!!!xx                                                               ",
   "                                       xx!!!xx                    xx xx                                       ",
   "                                        xx!xx                    x!!x!!x                                      ",
   "          xx                             xvx                    xx!!!!!xx                                     ",
   "                                                                 xx!!!xx                                      ",
   "                                                                  xx!xx                                       ",
   "                                                                   xvx                                        ",
   "                                                                                                              ",
   "      xx                                                                                                      ",
   "                                                                                                oo            ",
   "                    m                                                                                         ",
   "  x                xxx             o o                                                        xxx xxx      x  ",
   "  x               xxxxx       xx                                                             xxxxxxxxx     x  ",
   "  x             oxxxxxxxo     x    xxx                                                        xxxxxxx      x  ",
   "  x             xxxxxxxxx     xxxxxxxxxxx!!xxx      oo                                         xxxxx       x  ",
   "  x               xx xx       x         x!!xxx    xxxxxx    x    x    x     x                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
